### PR TITLE
feat(mcp): improve Claude Code ChatGPT browser consults

### PR DESCRIPTION
**Pull request by pdurlej**
## Summary

Adds a focused Claude Code / MCP browser-consult path without adding new MCP tools or changing unrelated API defaults.

- Adds MCP `consult` preset `chatgpt-pro-heavy`.
- Adds MCP `dryRun:true` so Claude/Codex can inspect the resolved Oracle run without opening Chrome or creating a session.
- Adds MCP `browserModelStrategy` passthrough for parity with the CLI.
- Adds `oracle bridge claude-config --local-browser` plus explicit `--oracle-home-dir` and `--browser-profile-dir` overrides for macOS/local Claude Code setups.
- Documents the "Let Them Fight" workflow: Claude Code asks Oracle, Oracle asks ChatGPT browser mode, and the answer returns through MCP.

The preset targets `gpt-5.5-pro` directly, matching the current upstream model support from #156.

## Public API

- MCP `consult`:
  - `preset?: "chatgpt-pro-heavy"`
  - `dryRun?: boolean`
  - `browserModelStrategy?: "select" | "current" | "ignore"`
- Bridge CLI:
  - `oracle bridge claude-config --local-browser`
  - `--oracle-home-dir <path>`
  - `--browser-profile-dir <path>`

## PR / Issue Map

- Builds on #156 for official GPT-5.5 / GPT-5.5 Pro model support.
- Complements #148 by giving Claude/Codex a better long-run browser consult path with heartbeat support when both land.
- Complements #150 because multiple MCP/CLI callers may share one browser profile.
- Complements #151 by exposing Deep Research/research-mode fields through the same MCP consult surface when that PR lands.
- Does not implement ChatGPT Project Sources management from #131 / #132.

## Validation

Latest branch head: `ab735615`; no code changes were needed in the final May 4 PR-body cleanup.

- `pnpm install --frozen-lockfile` -> passed, including prepare/build
- `pnpm vitest run tests/mcp/consult.test.ts tests/cli/bridgeClaudeConfig.test.ts` -> 2 files passed, 8 tests passed
- `pnpm run check` -> passed
- `pnpm run build` -> passed
- `pnpm test` -> 107 files passed / 18 skipped, 656 tests passed / 41 skipped
- `pnpm run test:mcp:unit` -> 5 files passed, 7 tests passed
- `pnpm run test:mcp:mcporter` -> passed
- MCP dry-run smoke: `preset:chatgpt-pro-heavy`, `dryRun:true` returned browser mode with `gpt-5.5-pro` and did not create a session or touch Chrome.
- `git diff --check` -> passed
- GitHub: mergeable, GitGuardian green

### CODE REVIEW

**Comment by pdurlej** [comment]
Rebuilt this branch cleanly on current `upstream/main` and pushed as `ab735615`.

Rebase notes:

- Dropped the old stacked GPT-5.5 browser/model commits that are now covered by #156.
- Kept this PR focused on MCP consult ergonomics and Claude Code local-browser config.
- Updated `preset:"chatgpt-pro-heavy"` to target the current `gpt-5.5-pro` model directly instead of the older `gpt-5-pro` alias.

Local validation on macOS:

- `pnpm install --frozen-lockfile` -> passed, including prepare/build
- `pnpm vitest run tests/mcp/consult.test.ts tests/cli/bridgeClaudeConfig.test.ts` -> 2 files passed, 8 tests passed
- `pnpm run check` -> passed
- `pnpm run build` -> passed
- `pnpm test` -> 107 files passed / 18 skipped, 656 tests passed / 41 skipped
- `pnpm run test:mcp:unit` -> 5 files passed, 7 tests passed
- `pnpm run test:mcp:mcporter` -> passed
- MCP dry-run smoke: `preset:chatgpt-pro-heavy`, `dryRun:true` returned browser mode with `gpt-5.5-pro` and did not create a session or touch Chrome.
- `git diff --check` -> passed

No secrets or account details included.

**Comment by pdurlej** [comment]
Final refresh from my side:

- No code changes in this last cleanup pass; I refreshed the PR body with the latest scope/test notes.
- Current head: `ab735615`.
- This remains intentionally narrow: MCP/Claude consult ergonomics and local Claude Code browser config, without pulling in the tab scheduler or Deep Research work.
- Previously validated with focused MCP/bridge tests, `pnpm run test:mcp:unit`, `pnpm run test:mcp:mcporter`, `pnpm run check`, `pnpm run build`, `pnpm test`, and dry-run consult coverage.
- GitGuardian is green and GitHub currently reports the PR as mergeable.

**Comment by steipete** [comment]
Thanks @pdurlej. I shipped the cleaned-up version of this on `main` as dbef347f.

What landed:

- `consult` preset `chatgpt-pro-heavy`, hard-coded to `gpt-5.5-pro` with heavy browser thinking by default.
- MCP `dryRun: true` support so callers can inspect the resolved Oracle run without opening Chrome or creating a session.
- MCP `browserModelStrategy` passthrough for parity with the CLI.
- `oracle bridge claude-config --local-browser` plus explicit local path overrides for same-Mac Claude Code + signed-in ChatGPT browser workflows.
- README, MCP docs, bridge docs, and changelog coverage.

I didn’t merge the PR branch directly because it had become stale against current `main` and included unrelated browser churn after recent merged work. I replayed the focused commits onto current `main` and added one fix while landing: bridge config generators now keep stdout machine-readable, so `oracle bridge claude-config --local-browser > .mcp.json` produces valid JSON instead of including the oracle banner/tip text. There is also a CLI regression test for that.

Validation before push:

- `pnpm vitest run tests/mcp/consult.test.ts tests/cli/bridgeClaudeConfig.test.ts` -> 9 passed
- `pnpm run check` -> passed
- `pnpm run build` -> passed
- `pnpm test` -> 109 files passed / 18 skipped, 703 tests passed / 42 skipped
- manual stdout parse for `node dist/bin/oracle-cli.js bridge claude-config --local-browser` -> valid JSON

Closing this PR because the cleaned-up implementation is now on `main`. Appreciate the focused MCP/Claude Code workflow work.
